defaults: &defaults
  secret_key_base: secret_key_base
  domain: miser.dev
  api_endpoint: miserapi.dev

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
  secret_key_base: more_secret_key_base
